name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-clang@v1
    - run: pip install fbp

    - name: Build
      run: fbp metro
      env:
        TERM: xterm-256color
