name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout submodule
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{secrets.SUBMODULE_TOKEN}}
        submodules: true
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-clang@v1
    - run: python3 BuildPy/__main__.py metro
      env:
        TERM: xterm-256color
